### PR TITLE
Moving to single function lodash import

### PR DESCRIPTION
**Pull request by jherr**
Bringing in lodash is a little heavyweight for something where the code might end up on the client.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by scsper** [comment]
:+1:

**Comment by scsper** [comment]
I'd merge this, except my write access was taken away when I left yahoo 😆 

@davglass, could you help out?

**Comment by juandopazo** [comment]
💥

**Pull request merged**
